# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MixtdAI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire'
	pod 'Kingfisher'
  pod 'UIGradient'
  pod 'IQKeyboardManagerSwift’
  pod 'SVProgressHUD'

  # Pods for MixtdAI

end
